language: python
cache: pip
env:
  - PIN_REQUIREMENTS=1
  - PIN_REQUIREMENTS=0
python:
  - "3.6"
matrix:
  # Failures here don't mark the build as failed
  allow_failures:
    - env: PIN_REQUIREMENTS=0
  # Don't wait for allowed failures before marking the build as finished
  fast_finish: true
install:
  if [ $PIN_REQUIREMENTS -eq 1 ]; then
    pip install --no-deps -r requirements/test.txt;
  else
    pip install .[test];
  fi
script:
  - pytest --cov=cellmlmanip --cov-config=cellmlmanip/.coveragerc
  - flake8
  - isort --verbose --check-only --diff --recursive cellmlmanip
after_success:
  - codecov
