name: Coverage
on: [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install
      run: |
        python --version
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install .[test]

    - name: Test coverage
      run: |
        python -m pytest --cov --cov-config=.coveragerc

    - name: Submit report to codecov
      uses: codecov/codecov-action@v1
      if: success()

