name: Style
on: [pull_request]
jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install tools
      run: |
        python --version
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install flake8 isort

    - name: Check code style
      run: |
        python -m flake8

    - name: Check imports are ordered correctly
      run: |
        python -m isort --verbose --check-only --diff cellmlmanip tests setup.py

