name: Pinned requirements
on: [pull_request]
jobs:
  unit-test-pinned:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install pinned dependencies
      run: |
        python --version
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements/test.txt

    - name: Install
      run: |
        python -m pip install --no-deps .

    - name: Run unit tests
      run: |
        python -m pytest

